version : "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: > # > signifies breaking the command onto next line
      sh -c "python manage.py run server 0.0.0.0:8000"  

